latent_dim: 128
max_steps: 100000
batch_size: 64
train_start_steps: 1000
train_interval: 10
total_episodes: 1000
save_model_interval: 100

## 画像を保存するときの設定
save_imgs: False
save_interval: 100
output_dir: './outputs_imgs'