latent_dim: 128
batch_size: 64
train_start_steps: 100
train_interval: 1
total_episodes: 10000
total_steps: 1000000
save_model_interval: 100

## 画像を保存するときの設定
save_imgs: False
save_interval: 100
output_dir: './outputs_imgs'
model_dir: './outputs_models'